### ISSUE TITLE
api 欄位名稱命名

### ISSUE THREAD

**Issue by wildfrontend** [antijava/menswalk#1]
<img width="715" alt="截圖 2020-05-11 上午8 30 55" src="https://user-images.githubusercontent.com/20965813/81514464-d6053e00-9361-11ea-96fd-5b89f0ee0440.png">

我發現 api 全都用 一個字母 表示欄位 可否改為更明確的命名？

**Comment by wildfrontend** [comment]
<img width="513" alt="截圖 2020-05-11 上午8 42 04" src="https://user-images.githubusercontent.com/20965813/81514737-4c567000-9363-11ea-94ec-00831f97a5b0.png">

api 路徑名稱也是 我覺得路徑可以明確表達 api 是用來找尋景點資訊

**Comment by antijava** [comment]
謝謝您提出 issue

我先說聲抱歉，因為 api 欄位命名真的是蠻主觀的

我的考量如下：
1.api json 是給程式讀的，不是給人看的，不用考慮易讀性
2.只用一個字母，減少查詢時回覆的「資料量」，希望可以提高一點點「傳輸速度」(例: address vs a)
3.各欄位的意義在 api 文件(swagger) 那裡已有解釋說明
4.api 欄位真的不多，只用一個字母也不會重覆

api 路徑名稱也是類似的考量
比起實際使用時呼叫「多次」的「URL 長度」
在開發時「少少幾次」的不明確
也就沒那麼在意了

**Comment by antijava** [comment]
對了
由於我那篇問題已經被擠出首頁了
而看起來也沒有什麼人有興趣動手做
所以我就選了 listenn08 為最佳解答
還請多多包涵

**Comment by wildfrontend** [comment]
@antijava  
api 命名部分好吧我覺得可以，我前端在rename 好了。

關於 HTTP  Method 部分可以改用 RESTful API 風格嗎？ 我看文件還真的沒注意到有`新增` API
而且新增如果用 `GET` 應該會亂傳資料進api吧？如果我刻意改參數的話

最佳解答部分 我沒關係，我主要是剛好做 side project，能參與open source 就可以了

**Comment by antijava** [comment]
這裡的「RESTful API 風格」是指
「新增的 API 用 POST 而不要用 GET 寫」是嗎？

我會再找時間改

- [ RESTFul API 風格的 新增]

**Comment by antijava** [comment]
RESTFul API 的新增我已修改
並修改 swagger API 文件

註：因為 listennn08 已經寫了用 GET 方式使用新增的 API
所以我先改成「POST/GET 兩者並行」的方式
等我通知 listennn08 把 GET 改成 POST 之後
我再拿掉程式中 GET 的部份

**Comment by antijava** [comment]
@wildfrontend 
還有一件小事
如果您打算將 source code 放一份在這兒的話
請放在 frontend/wildfrontend 目錄之下
(以便之後還可以並存其他人寫的)
謝謝
