### ISSUE TITLE
APi的遊客統計問題

### ISSUE THREAD

**Issue by wildfrontend** [antijava/menswalk#8]
@antijava  我一開始也是想說做地圖的相關應用，當初也是想說作法跟 @listennn08  一樣
但專案的重點是方便查詢景點當天的遊客人數，所以我認為地圖是其次，主要是統計資料，我構想是比較偏向於思考怎麼讓顧客查詢景點(ex:似乎用search bar 查景點就可以了，地圖反而到不需要) 

我發現你給的範例也是比較偏向於統計，如[迪士尼](http://www15.plala.or.jp/gcap/disney/)是統計一個月份裡每天的人數。

如果照 迪士尼的設計 那查詢日期反而是前端這邊的主要功能而不是用地圖顯示景點位置？ 

我認為這樣做的話會比較像是做預約系統，遊客預約什麼時候去哪個景點玩，然後也可以查詢當天景點的人數統計。

**Comment by antijava** [comment]
沒錯，我的想法跟你一樣，比較像是「預約系統」

只有在「預約去玩」的時侯，可以考慮不同的介面
例如：日期，可以用打字的也可以用日曆介面來點選
景點：可以下拉選擇、用搜尋也可以用地圖來點選

**Comment by wildfrontend** [comment]
@antijava 感謝回覆

**Comment by listennn08** [comment]
我其實一開始是只打算做統計人數的部分
不過看到 @antijava 大寫說旅遊地圖才去看地圖怎麼做
不過結合地圖我想也不錯
可以看要去的地方周邊的景點是不是也很多人
